### ISSUE TITLE
Cannot make text work

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/just-your-type#1]
Hello Thomas,
I want to have my cursive text go right and san serif text go left but it's not working. Do I have to add another grid to make this work?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you tried using the `.text-right` class on the units that surround the cursive text?

**Comment by fuen0015** [comment]
that did work but now the text at the small screens are affected and no longer in the middle

**Comment by thomasjbradley** [comment]
So, media queries, I suppose.

**Comment by thomasjbradley** [comment]
Add a class to that same element then use the media queries to affect the text alignment.

**Comment by fuen0015** [comment]
Thank you I will give it a try
